name: Check and Test

on:
  push:
    branches:
      - "main"
    paths:
      - '**/*.h'
      - '**/*.c'
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    container:
      image: gcc:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cppcheck
        run: |
          apt-get update
          apt-get install -y cppcheck
        
      - name: Run MISRA check
        run: |
          make misra

      - name: Run automated tests
        run: |
          make test
