name: C/C++ Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    container:
      image: gcc:11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
        
      - name: Run Analysis Script (test.sh)
        run: |
          chmod +x test.sh
          ./test.sh NODOXY
