name: C/C++ Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    container:
      image: gcc:11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cppcheck
        run: |
          apt-get update
          apt-get install -y cppcheck
        
      - name: Run Analysis Script (test.sh)
        run: |
          chmod +x test.sh
          ./test.sh NODOXY
